export const baseUrl = "http://127.0.0.1:8000/api";
// export const baseUrl = "https://fast-cliffs-03764.herokuapp.com/api";
export const todoPath = `${baseUrl}/todo/`;
export const todoItemPath = `${baseUrl}/todo/list/`;
export const userPath = `${baseUrl}/user/`;
export const loginPath = `${baseUrl}/user/login/`;
export const logoutPath = `${baseUrl}/user/logout/`;
export const checkPath = `${baseUrl}/user/check/`;
export const registerPath = `${baseUrl}/user/register/`;
